/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Yuka: typeof import('./src/yuka')['Yuka']
  const useYuka: typeof import('./src/yuka')['useYuka']
}
